package edugame.token;

public enum TipoToken {

    JUEGO, ESCENA, INICIAR, BUCLE, DIBUJAR,
    SI, SINO, REPETIR, MIENTRAS,
    AL_PRESIONAR, AL_SOLTAR, AL_CLICK, AL_TOCAR,
    FIN,

    PERSONAJE, OBJETO, FONDO, SONIDO,
    MOVER, MOSTRAR, OCULTAR,
    REPRODUCIR, DETENER,
    GUARDAR,

    IMAGEN, EN, ARCHIVO,
    DERECHA, IZQUIERDA, ARRIBA, ABAJO,
    TECLA, VECES,

    Y, O, NO,

    NUMERO_KW, TEXTO_KW, VERDADERO, FALSO,

    NUMERO_ENTERO,
    NUMERO_DECIMAL,
    CADENA,

    IDENTIFICADOR,

    OP_SUMA,
    OP_RESTA,
    OP_MULT,
    OP_DIV,
    OP_MAYOR,
    OP_MENOR,
    OP_IGUAL,
    OP_MAYOR_IGUAL,
    OP_MENOR_IGUAL,

    PUNTO_COMA,
    PARENTESIS_ABR,
    PARENTESIS_CIE,
    COMA,
    DOS_PUNTOS,

    FIN_ARCHIVO,
    DESCONOCIDO,
    DIMENSION
}